site_name: San
site_url: https://astrocorp.net
repo_url: https://github.com/astrocorp42/san

site_dir: dist

theme:
  name: null
  custom_dir: '.mkdocs-material/material'
  language: en
  feature:
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

nav:
  - index.md
  - implementations.md
  - san-vs.md
  - versions/v0.1.0.md
